### ISSUE TITLE
Lengths of sequences

### ISSUE THREAD

**Issue by Tesserazoa** [vaulot/pr2_database#6] opened 2018-03-02 13:24 UTC
Hello, I am afraid this may be a naive query rather than an issue. If the former, then I am sure it can be closed and discarded quickly. I have been running a large dataset against SILVA and PR2 (an older version, but my question still pertains) and looking to reconcile the two results for each. I ran into a few cases where I could not understand how I could be getting high identity matches to such different things in the two databases. In several of these cases, I retrieved the sequences from Genbank to align with the relevant OTUs and found a set of cases where our OTU was not matching as well to the Genbank entry as compared to the sequence with that same Genbank accession from PR2. I traced several of our problem cases to similar instances to situations where the PR2 sequence with AccessionX was longer than the sequence associated with AccessionX in Genbank. The PR2-version4.9.2 appears to have more than 1000 sequences that are greater than 100 bp longer than the associated Genbank sequence. Is this expected? I apologize if this is a silly question. I am just new to this type of analysis.

**Comment by vaulot** [comment] 2018-03-05 14:45
Hello
Thanks for your feedback.  

If you could post an example with:
1. Your OTUs (5 will be OK)
2. The GenBank sequences matching them
3. The PR2 sequences that are longer than the Genbank equivalent
Thanks a lot in advance.

**Comment by Tesserazoa** [comment] 2018-03-05 15:13
Great. Thanks. Will do in the next couple of hours.
Cheers,
--Allen

Dr. Allen G. Collins<http://invertebrates.si.edu/staff/collins.cfm>
Zoologist & Director, NOAA’s National Systematics Lab<http://www.nefsc.noaa.gov/nefsc/systematics>
Allen.Collins@NOAA.gov

SMITHSONIAN INSTITUTION
NATIONAL MUSEUM OF NATURAL HISTORY
Dept of Invertebrate Zoology<http://invertebrates.si.edu/index.htm>, MRC-163
10th & Constitution Aves. NW
Washington DC 20560
w 202.633.0645

**Comment by Tesserazoa** [comment] 2018-03-05 21:56
Here some examples:
>OTU_2493541
AGCTCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATTTCGGAATGGGCCAGCTGGTCTGCCGTGAGGTGTGTTACTGACTGGTCTGTTCTTCTTCGCAAAGACTGCGTGTGCTCTTTATTGAGTGTGCGTAGGATTTACGACGTTTACTTTGAAAAAATTAGAGTGTTCAAAGCAGGCTATTGCTTGAATACATGAGCATGGAATAATGGAATAGGACTTTGGTCCCATTTTGTTGGTTTCTAGGACCGAAGTAATGATTAAGAGGGACAATTGGGGGCATCCGTATTTCGTTGTCAGAGGTGAAATTCTTGGATTTACGAAAGACGAACTACTGCGAAAGCATTTGCCAAGAATGTTT
97.9% match to: EF526734.1.1556 in PR2, but only 72% to that sequence obtained directly from GenBank. The PR2 length is 2611. 

>OTU_11785
AGCTCCAATAGCGTATATTTAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATTTCGGGTAGGGGGCGCCGGTCCGCTTCGGTGTGCACTGGCGGCCCATATCTTCTTGTCGGGGATGCGTGCTGGTCTTCATTGATCGGCCGCAGAGTCGGCGCAGTTACTTTGAAAAAATTAGAGTGTTCAAAGCAGGCTTTCGCTTGAATACATTAGCATGGAATAACATGATAGGACTCCGTTCTCATTGTGTTGGTCTTCGAGACTGGAGTAATGATTAAGAGGGACAGTTGGGGGCATTCGTATTTCATTGTCAGAGGTGAAATTCTTGGATTTATGAAAGACGAACTTCTGCGAAAGCATTTGCCAAGGATGTTT
97% match to FJ350428.1.1043 in PR2, but only 78% to that sequence obtained directly from GenBank. The PR2 length is 2788. 

>OTU_9687
AGCTCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATCTCAGGTCCGAGCTGGTGGTCTGCCTTTTGGGGCAGTTTACTGCCTGTCTCGACCTCGCTTTTGCGGTCCGCTCTGGGTTCTCTTAACTGAGTGCTCTGGGTGTCCGCAACGTTTACTTTGAAAAAATTAGAGTGTTCAAAGCAGTCTGAATGACTGAATAATGGTGCATGGAATAATGGAATAGGACCTCGGTTCTATTTTGTTGGTTTTCGGAACTTGAGGTAATGATTAAGAGGGACAGACGGGGGCATTCGTATTGCGCCGTTAGAGGTGAAATTCTTGGATCGGCGCAAGACGAACAACTGCGAAAGCATTTGCCAAGAATGTTT
98% match to HM991452.1.854 in PR2, but low match to that sequence obtained directly from GenBank. The PR2 length is 2595. 

>OTU_90858
AGCTCCAATAGCGTATATTAATGTTGTTGCAGTTAAAAAGCTCGTAGTTGGATTTCTGCGTCGCGCATTTCAGTCCGCCGCATCGCGGTGCGACTGGTTTGGAGCGTCGCATCCTTGTGGAGATTGTCGGGGCCATTGATTTGGTCTTTTCCGTCAGGAACCGCATCGTTTACTGTGAAAAAATTAGAGTGTTCAAAGCAGGCTTATGCCGTGAATACATTAGCATGGAATAATAAGATAGGACTTTGGTTCTATTTTGTTGGTTGGAGGCCAAGGTAATGATTAATAGGGACAGTTGGGGGTATTCATATTTAATTGTCAGAGGTGAAATTCTTGGATTTATGAAAGATGAACTTATGCGAAAGCATTTACCAAGGATGTTT
95% match to EF622809.1.2279_U in PR2, but low match to that sequence obtained directly from GenBank. The PR2 length is 3166. 

Thanks again for your help.
--Allen

**Comment by Tesserazoa** [comment] 2018-03-05 22:02
Sorry. That was only 4. Here is one more.

>OTU_7836
AGCTCCAATAGCGTATATTAAAGTTGTTGCGGTTAAAAAGCTCGTAGTTGGAGTTCTGCCAGGTGACGCTCGTCCGCCCAAGTGGTGTGTACAGGGCGTGCATCTGGCCCTTTCAAGGGGAACGTGTCTGCACTTTACTGTGTGGTGCGAGATCCTTGACTTTTACTTTGAGGAAATCAGAGTGTTCCAAGCAGGCTCTCGTCGTGTATAGCTCAGCATGGAATAATAGCATTGGACTTCGTTTCTAAGCTGTTGGTTGCAAGAAGCGAGGTAATGATGAAGAGGGATAGTTGGGGGCATTCGTATTTAACTGTCAGAGGTGAAATTCTTGGATTTGTTAAAGACGGACTACTGCGAAAGCATCTGCCATGGATGTTT
100% match to AJ830876.1.1862 in PR2. The PR2 length is 3393 bp.

I am wondering if these can be "in silico chimeras".

**Comment by vaulot** [comment] 2018-03-05 22:14
Thanks Allen for the sequences. 
Two quick question:
* Which FASTA file format did you use to perform the BLAST
* What software are you using to perform the BLAST

**Comment by Tesserazoa** [comment] 2018-03-05 22:20
We originally set up a local BLAST (BLASTn) to this: "pr2_mothur_version_4.5.0.zip".
But I tested each of the examples against these sequences: "pr2_version_4.9.2_mothur.fasta.gz".

**Comment by vaulot** [comment] 2018-03-06 12:56
Dear Allen

 I could reproduce your problem.  I think this was due to a problem when I imported the original PR2 files into my database and some sequences were artificially expanded (the start of the PR2 sequence match the GenBank sequence but after there are extra bases).  I will try to come with a fix in the next couple of days.  By chance I have still a back up of the 2011 database and I will fix the sequences that are bad.

Thanks again for the precious feedback.  Daniel

**Comment by vaulot** [comment] 2018-03-07 22:59
Dear Allen

This problem has been fixed in the latest release 4.10.0.  Let me know if you see other problems.

**Comment by Tesserazoa** [comment] 2018-03-07 23:46
Certainly. Thanks very much.

Dr. Allen G. Collins<http://invertebrates.si.edu/staff/collins.cfm>
Zoologist & Director, NOAA’s National Systematics Lab<http://www.nefsc.noaa.gov/nefsc/systematics>
Allen.Collins@NOAA.gov

SMITHSONIAN INSTITUTION
NATIONAL MUSEUM OF NATURAL HISTORY
Dept of Invertebrate Zoology<http://invertebrates.si.edu/index.htm>, MRC-163
10th & Constitution Aves. NW
Washington DC 20560
w 202.633.0645

**Closed** 2018-03-08 13:04 UTC
